<a href="https://colab.research.google.com/github/aaubs/ds-master/blob/main/courses/ds4b-m1-1-intro/notebooks/s1-data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Peeface

## Why Python?
1. General purpose language - add what you need
2. Portable (Linux, Windows, Mac)
3. Interactive
4. Free
5. Community and eco-system
6. Easy to use

## Working with Python
Workflows - many - find your own! In this course - Jupyter notebook and Pandas:
* Python + Jupyter notebook + Pandas = A complete environment
* Interactive
* Encourage an iterative work process (research?)
* Documentation, code and visualization in one - literate programming
* Reproducing results and figures

# Introduction

In this session, you will learn the basic Python syntax for data manipulation & analysis, including:

1. General syntax
2. basic operations
3. Object & data types
4. Flow controls




In [1]:
import numpy as np # Basic library for all kind of numerical operations
import pandas as pd # Basic library for data manipulation in dataframes

# Basics

## The very basics

In [55]:
# Running a cell (Ctrl-Enter, Shift-Enter)
print('Hello world')

Hello world


## Variables

In [ ]:
i = 6
print(i, type(i))

In [ ]:
x = 3.2
print(x, type(x))

In [ ]:
s = 'Hello'
print(s, type(s))

## Value assignment & evaluation

In [3]:
x = 3         # Assignment
print('We asigned x the value of ', x)              # Evaluate the expression and print result

We asigned x the value of  3


In [4]:
y = 4         # Assignment
y + 5         # Evaluation, y remains 4

9

In [5]:
z = x + 17*y  # Assignment
z             # Evaluation

71

## Value comparison

Comparisons return boolean values: True or False

In [8]:
2==2  # Equality

True

In [9]:
2!=2  # Inequality

False

In [10]:
x <= y # less than or equal: "<", ">", and ">=" also work

True

In [11]:
(x | z) >= y

True

In [12]:
(x & z) >= y

False

## Special Constraints, NA, NaN, Inf

In [17]:
print([1, None, 3])

[1, None, 3]


## Importing
We need to import libraries or only parts of libraries all the time. Use name-conventions when doing so

In [56]:
from math import sqrt

In [78]:
a = 2
b = 3

c = sqrt(a**2 + b**2)
print(c)

3.605551275463989


## Functions
* Define a function
* Function name: pythagoras
* Arguments: a, b
* Indentation using tab (4 spaces) for the whole function
* `return` statement

In [79]:
def pythagoras(a, b):
    return sqrt(a**2 + b**2) # Notice the tab!

In [80]:
print(pythagoras)

<function pythagoras at 0x7fd7a5d76ef0>


In [82]:
c = pythagoras(a, b)
print(c)

3.605551275463989


## Mini-assignment
* Construct a function that given two points $(x_1, y_1), (x_2, y_2)$ on a line computes the slope $a$ of the line
$$ y = ax + b$$
given by
$$ a = \frac{y_2- y_1}{x_2 - x_1}$$



#Object classes


## Vector

One-dimensional collection of values

In [21]:
# Numeric
v1 = [1,5,11,33] # [] initiate a list
v1

[1, 5, 11, 33]

In [22]:
# String
v2 = ["hello","world"]
v2

['hello', 'world']

In [23]:
# Boolean
v3 = [True, True, False, True]
v3

[True, True, False, True]

Evaluating elements in vectors

In [91]:
v1[0]

1

In [92]:
v1[1:3]

[5, 11]

Combining different types of elements you obtain a list of lists (later) with all elements in their original format

In [93]:
v5 =[v1, v2, v3]
v5 
# Integers (numbers) are still numbers, not strings (text). Easy to see because they don't have ' '

[[1, 5, 11, 33], ['hello', 'world'], [True, True, False, True]]

Adding vectors will append them (not sum them)

In [28]:
v1 + v3

[1, 5, 11, 33, True, True, False, True]

In [39]:
# Same for multiplication
v1 * 2

[1, 5, 11, 33, 1, 5, 11, 33]

**Element-wise operations:** To do numerical operations on vectors
numpy.arrays. NumPy is a library, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. Here, you can already see that Python is a CS language.

In [42]:
v1_array = np.array(v1)
v2_array = np.array(v2)
v3_array = np.array(v3)

In [44]:
v1_array

array([ 1,  5, 11, 33])

In [48]:
v1_array + 5

array([ 6, 10, 16, 38])

In [49]:
v1_array + v3_array

array([ 2,  6, 11, 34])

In [52]:
# Arrays of different size
v1_array + np.array([1,7])

ValueError: ignored

In [54]:
# non-numerical arrays
v1_array + v2_array

UFuncTypeError: ignored

**Mathematical operations over the vector:** For most maths you need to engage numpy or other modules (Python is not per sea maths language)

In [84]:
# that works the same way
np.sum(v1)

50

In [85]:
np.mean(v1)

12.5

In [86]:
# Standard deviation for population - DeltaDegreesOfFreedom = 0 by default
np.std(v1, ddof=0)

12.359207094308275

In [87]:
np.std(v1, ddof=1)

14.27118308573843

In [89]:
np.corrcoef(v1,v1)

array([[1., 1.],
       [1., 1.]])

Also consider this cheat sheet

https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

## Lists
* An indexable collection of variables (objects)
* C-style or 0-indexed

In [94]:
l = ['Caroline', 1.0, pythagoras]
type(l)

list

In [96]:
l

['Caroline', 1.0, <function pythagoras at 0x7fd7a5d76ef0>]


In [98]:
l[0]

'Caroline'

In [97]:
type(l[0])

str

Common methods for lists

In [99]:
l.append(sqrt(2.0))
l

['Caroline', 1.0, <function __main__.pythagoras(a, b)>, 1.4142135623730951]

In [100]:
a = l.pop(2)
a

<function __main__.pythagoras(a, b)>

In [101]:
l.pop(0)
l.append(100)
l.sort(reverse=True)

In [102]:
l

[100, 1.4142135623730951, 1.0]

In [103]:
l[1] = 2
l

[100, 2, 1.0]

In [106]:
l.extend([6.0, 4])
l

[100, 2, 1.0, 6.0, 4, [6.0, 4], 6.0, 4]

## Tuples
* Immutable "lists"

In [107]:
t = (1.0, 4.0)
t, type(t)

((1.0, 4.0), tuple)

In [108]:
t[1]

4.0

In [109]:
t[1] = 2

TypeError: ignored

## Dictionaries
- Like lists with user-definable indices
- Can, like lists and tuples, contain a mix of different types of data.
- The indices can *also* be different kinds of data - unlike lists and tuples.

In [129]:
d = {'one': 1, 2: 1 + 1, 3.0: 'three'}
d

{'one': 1, 2: 2, 3.0: 'three'}

Usefull methods

In [130]:
d.keys()

dict_keys(['one', 2, 3.0])

In [131]:
d.items()

dict_items([('one', 1), (2, 2), (3.0, 'three')])

In [125]:
some_value = d.pop(3.0)
d

{'one': 1, 2: 2}

In [126]:
some_value

'three'

In [127]:
d['four'] = 4
d

{'one': 1, 2: 2, 'four': 4}

In [132]:
d.update({'five': 5.0, 6: 6.0})
d

{'one': 1, 2: 2, 3.0: 'three', 'five': 5.0, 6: 6.0}

## Data Frames

In Python Data Frames are managed by Pandas, a very comprehensive library for data manipulation and analysis

https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [135]:
# We construct the DF from a dictionary which is indicated by {'some_key':['some_values']}

df1 = pd.DataFrame(
    {'ID':range(1,5), # Python counts from 0 and the last value in a range is excluded
     'FirstName':["Jesper","Jonas","Pernille","Helle"],
     'Female':[False,False,True,True],
     'Age':[22,33,44,55]
})

In [136]:
# Python doesn't really do much factors and as you can see pandas understood your input formats
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ID         4 non-null      int64 
 1   FirstName  4 non-null      object
 2   Female     4 non-null      bool  
 3   Age        4 non-null      int64 
dtypes: bool(1), int64(2), object(1)
memory usage: 228.0+ bytes


In [137]:
df1.FirstName #dot notation

0      Jesper
1       Jonas
2    Pernille
3       Helle
Name: FirstName, dtype: object

In [138]:
df1['FirstName'] #more traditional subsetting

0      Jesper
1       Jonas
2    Pernille
3       Helle
Name: FirstName, dtype: object

In [139]:
df1.loc[:,'FirstName'] #more complex subsetting

0      Jesper
1       Jonas
2    Pernille
3       Helle
Name: FirstName, dtype: object

In [140]:
df1.iloc[:,1] #index based

0      Jesper
1       Jonas
2    Pernille
3       Helle
Name: FirstName, dtype: object

In [141]:
# Rows 1 and 2, columns 3 and 4 - the gender and age of Jesper & Jonas
df1.iloc[[0,1],[2,3]]


Female  Age
0   False   22
1   False   33

In [142]:
#Same thing
df1.loc[[0,1],['Female','Age']]

Female  Age
0   False   22
1   False   33

In [143]:
# Rows 1 and 3, all columns

df1.iloc[[0,2],:] # don't forget to count index-1 when going from R to python

ID FirstName  Female  Age
0   1    Jesper   False   22
2   3  Pernille    True   44

In [144]:
#Find the names of everyone over the age of 30 in the data
df1[df1.Age > 30]

ID FirstName  Female  Age
1   2     Jonas   False   33
2   3  Pernille    True   44
3   4     Helle    True   55

In [145]:
# or "Query style" (There are always many ways of doing the same thing)
df1.query('Age > 30')

ID FirstName  Female  Age
1   2     Jonas   False   33
2   3  Pernille    True   44
3   4     Helle    True   55

## 2.2.6 Flow Control (loops & friends)

Python is made for readability and therefor tabs and new lines have syntax meaning


In [ ]:
x = 5 
y = 10

if (x==0):
  y = 0 
else:
  y = y/x  
  print(y)

In [ ]:
for i in range(1,x+1):
  print("OMG, i just counted to " + str(i))

In [ ]:
while x > 0:
  print(x) 
  x = x-1

In [ ]:
while True: 
  print(x)
  x = x + 1
  if x > 7:
    break

In [133]:
even = [] # empty list
for i in range(10):
    even.append(i*2)
even

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [134]:
odd = []
for i in even:
    odd.append(i+1)
odd

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

### Mini-assignment
.....